# Generated by Django 5.0.1 on 2024-04-27 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rsvpentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvpentry',
            name='invite',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
