# Generated by Django 5.0.1 on 2024-04-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rsvpentry_invite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvpentry',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
