# Generated by Django 5.0.1 on 2024-05-05 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_rsvpentry_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvpentry',
            name='babysitter',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='rsvpentry',
            name='dietary_restrictions',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rsvpentry',
            name='meal',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rsvpentry',
            name='pizza',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='rsvpentry',
            name='pizza_meal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rsvpentry',
            name='stay',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='rsvpentry',
            name='welcome_dinner',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='rsvpentry',
            name='welcome_meal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rsvpentry',
            name='attending',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rsvpentry',
            name='invite',
            field=models.IntegerField(null=True),
        ),
    ]
