# Generated by Django 5.0.1 on 2024-05-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_rsvpentry_is_child'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvpentry',
            name='attending',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rsvpentry',
            name='babysitter',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rsvpentry',
            name='meal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rsvpentry',
            name='pizza',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rsvpentry',
            name='stay',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rsvpentry',
            name='welcome_dinner',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
