# Generated by Django 5.0.1 on 2024-10-05 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_rsvpentry_song_request_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RsvpEntry',
        ),
    ]
